### ISSUE TITLE
Add !takematrix command

### ISSUE THREAD

**Issue by pacpix** [EchoFrost/BernkeBotV2#11]
This command is a simple text command that documents the meanings of the different matrix quadrants
```
elif message.content.startswith('!takematrix'):
        msg = 'Q1 = Hot and Right, Q2 = Hot and Wrong, Q3 = Cold and Wrong, Q4 = Cold and Right'.format(message)
        yield from channel.send(msg)
```

**Comment by EchoFrost** [comment]
Note for repository auditors:
This task was completed in the initial commit of the repository.

Ref. commit hash: [aa862598739b9c4a9f6d34880fb363f2ec17c30f](https://github.com/EchoFrost/BernkeBotV2/commit/aa862598739b9c4a9f6d34880fb363f2ec17c30f)

**Comment by pacpix** [comment]
used as a test case due to the relative command architecture simplicity
